### ISSUE TITLE
Unable to remove custom roles at tenant root.

### ISSUE THREAD

**Issue by autocloudarc** [Azure/ALZ-PowerShell-Module#143]
When I attempt to remove the custom roles staged a the tenant root from my destroy operation, I am unable to do so and receive no detailed information of the problem. 

### Expected Behavior

I should be able to remove custom roles deployed by the solution, otherwise, I will receive an error when I attempt to redploy if the custom roles already exist.

### Current Behavior

I receive a message in the notification area which states: "Failed to remove role definition(s)
Failed to remove role with name Azure Landing Zones Subscription Owner (alz-mgmt) : An error occurred. Please try again later."

### Steps to Reproduce

1. Navigate to the tenant root management group.
2. Select IAM
3. Select Roles tab
4. Filter to view Custom roles
5. From the elipses on the right of any displayed custom role, select delete.

Alternatively, run this PowerShell script in the cloud shell:

```powershell
$customRoles = @("Azure Landing Zones Management Group Contributor (alz-mgmt)","Azure Landing Zones Subscription Owner (alz-mgmt)","Azure Landing Zones Subscription Reader (alz-mgmt)")
$customRoles | ForEach-Object -Process {Get-AzRoleDefinition $_ | Remove-AzRoleDefinition -Force -Verbose }
```

Input file:
```yml

# Basic inputs
# The Infrastructure as Code (IaC) tool to use for the deployment. (e.g. 'terraform'). NOTE: Only 'terraform' is relevant here.
iac: "terraform"
# The bootstrap module to use for version control system to use for the deployment. (e.g. 'alz_github')
bootstrap: "alz_github"
# The starter module to use for the deployment. (e.g. 'complete')
starter: "complete"

# Bootstrap inputs
# The personal access token for GitHub:
github_personal_system_access_token: <redacted>
github_organization_name: "<redacted>arc"

# Controls whether to use a separate repository to store pipeline templates. This is an extra layer of security to ensure that the azure
# credentials can only be leveraged for the specified workload
use_separate_repository_for_templates: "true"
# Azure Subscription ID for the bootstrap resources (e.g. storage account, identities, etc). Leave empty to use the az login subscription
# (A valid subscription id GUID e.g. '12345678-1234-1234-1234-123456789012')
bootstrap_subscription_id: "<redacted>23c"
# Used to build up the default resource names (e.g. rg-<service_name>-mgmt-uksouth-001) (A valid Azure name with no hyphens and limited
# length e.g. 'abcd')
service_name: "alz"
# Used to build up the default resource names (e.g. rg-alz-<environment_name>-uksouth-001) (A valid Azure name with no hyphens and limited
# length e.g. 'abcd')
environment_name: "mgmt"
# Used to build up the default resource names (e.g. rg-alz-mgmt-uksouth-<postfix_number>) (A number e.g. '1234')
postfix_number: "1"
# Controls whether to use self-hosted agents for the pipelines
use_self_hosted_agents: "true"
# Personal access token for GitHub Runners to register themselves: alz-tfm-pat-02
github_runners_personal_access_token: <redacted>                                
# Controls whether to use private networking for the agent to storage account communication
use_private_networking: "true"
# Allow access to the storage account from the current IP address. We recommend this is kept off for security
allow_storage_access_from_my_ip: "true"
# Apply stage approvers to the action / pipeline, must be a list of SPNs separate by a comma (e.g. abcdef@microsoft.com,ghijklm@microsoft.com) using team "alz-mgmt-approvers"
apply_approvers: "<redacted>@outlook.com"
# Create branch policies for the main branch
create_branch_policies: "true"

# Shared interface inputs
# Azure Deployment location for the bootstrap resources (e.g. storage account, identities, etc)
# (An Azure deployment location e.g. 'uksouth')
bootstrap_location: "eastus2"
starter_location: "eastus2"
# The root parent management group display name. This will default to 'Tenant Root Group' if not supplied
root_parent_management_group_display_name: "Tenant Root Group"
# This is the id of the management group that the ALZ hierarchy will be nested under, will default to the Tenant Root Group
# (A valid Azure name e.g. 'my-azure-name')
root_parent_management_group_id: "<redacted>8f9"
# The identifier of the Identity Subscription. (e.g '00000000-0000-0000-0000-000000000000')
# (A valid subscription id GUID e.g. '12345678-1234-1234-1234-123456789012')
subscription_id_identity: "<redacted>310"
# The identifier of the Management Subscription. (e.g 00000000-0000-0000-0000-000000000000)
# (A valid subscription id GUID e.g. '12345678-1234-1234-1234-123456789012')
subscription_id_management: "<redacted>c5f"
# The identifier of the Connectivity Subscription. (e.g '00000000-0000-0000-0000-000000000000')
# (A valid subscription id GUID e.g. '12345678-1234-1234-1234-123456789012')
subscription_id_connectivity: "<redacted>8dc"

# Starter Module Specific Variables
# The location for Azure resources. (e.g 'uksouth')
# (An Azure deployment location e.g. 'uksouth')
default_location: "eastus2"
# The default postfix for Azure resources. (e.g 'landing-zone') #
# (A valid Azure name e.g. 'my-azure-name')
default_postfix: "landing-zone"
# The path of the configuration file
# (A valid yaml or json configuration file path e.g. './my-folder/my-config-file.yaml' or `c:\\my-folder\\my-config-file.yaml`)
configuration_file_path: ""
```

### Context (Environment)

I am practicing the deployments and rollbacks to demonstrate the functionality for customers and during the Azure Landing Zone Deployment VBD engagements.

* Operating System and version as reported by `$PSVersionTable.OS`:
* PowerShell versions as reported by `$PSVersionTable.PSEdition`:

PS /home/system> $PSVersionTable                                                                                            

Name                           Value
----                           -----
PSVersion                      7.4.4
PSEdition                      Core
GitCommitId                    7.4.4
OS                             CBL-Mariner/Linux
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

I can't delete custom roles deployed by this solution to clean up the tenant, which is a blocker for performing subsequent deployments, demonstrating for customer and for engagements.

### Detailed Description

After running the "02 Azure Landing Zones Continuous Delivery " GitHub Actions workflow with the 'destroy' parameter to cleanup my previous deployments, I am unable to remove the custom roles from the tenant root. Deployment region is eastus2, although I don't believe roles are region specific resources. See screenshot below:

![unable-to-delete-custom-roles-at-tenant-root](https://github.com/user-attachments/assets/b0012192-5500-43ed-b145-fcf68a461cca)
