### ISSUE TITLE
Bug: complete_vnext fails because resource group doesn't exist

### ISSUE THREAD

**Issue by andrew-flatters-bliss** [Azure/ALZ-PowerShell-Module#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bootstrap or Starter Module Deployment? (Required)

starter_module

### ALZ-PowerShell-Module Version (Required)

1.1.6

### alz-terraform-accelerator Version (Required)

1.1.2

### Starter Module (Required)

complete_vnext

### Input arguments of the ALZ-PowerShell-Module (Required)

```YAML
{
  "allow_storage_access_from_my_ip": "true",
  "apply_approvers": "**@**.co.uk",
  "azure_devops_authentication_scheme": "WorkloadIdentityFederation",
  "azure_devops_create_project": "true",
  "azure_devops_organization_name": "Bliss-Infrastructure",
  "azure_devops_personal_access_token": "***",
  "azure_devops_project_name": "BlissLzAccelerator",
  "azure_devops_use_organisation_legacy_url": "false",
  "bootstrap_location": "uksouth",
  "bootstrap_subscription_id": "**f8738ede218f",
  "environment_name": "prd",
  "postfix_number": 1,
  "root_parent_management_group_display_name": "Tenant Root Group",
  "service_name": "blisslz",
  "starter_module": "complete_vnext",
  "use_private_networking": "true",
  "use_self_hosted_agents": "true",
  "use_separate_repository_for_pipeline_templates": "true"
}

{
  "configuration_file_path": "",
  "default_location": "uksouth",
  "default_postfix": "blisslz",
  "root_parent_management_group_id": "",
  "subscription_id_connectivity": "**f8738ede218f",
  "subscription_id_identity": "**f8738ede218f",
  "subscription_id_management": "**f8738ede218f"
}
```

### Debug Output/Panic Output (Optional)

```shell
module.management_groups_layer_1["root"].alz_policy_role_assignments.this: Creating...
╷
│ Error: Client Error
│ 
│   with module.management_groups_layer_1["root"].alz_policy_role_assignments.this,
│   on .terraform/modules/management_groups_layer_1/main.tf line 196, in resource "alz_policy_role_assignments" "this":
│  196: resource "alz_policy_role_assignments" "this" {
│ 
│ Unable to create role assignment, got error: PUT
│ https://management.azure.com/subscriptions/ac44928a-0ab8-4fa3-8131-f8738ede218f/resourceGroups/rg-management-blisslz/providers/Microsoft.OperationalInsights/workspaces/law-blisslz/providers/Microsoft.Authorization/roleAssignments/238c9154-867e-5ef1-9e95-41b841e6ada9
│ --------------------------------------------------------------------------------
│ RESPONSE 404: 404 Not Found
│ ERROR CODE: ResourceGroupNotFound
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "ResourceGroupNotFound",
│     "message": "Resource group 'rg-management-blisslz' could not be found."
│   }
│ }
│ --------------------------------------------------------------------------------
│ 
╵
##[error]Script failed with exit code: 1
```

### Expected Behaviour (Required)

Resource Group should be created before it's trying to be referenced

* Suspect this is because the modules are taken in by name looking at the plan rather than referencing the resource group module 

### Actual Behaviour (Required)

Errors on a different module as the resource group hasn't been created yet

### Steps to Reproduce (Optional)

Run the accelerator CI/CD  step 2 for actual provisioning to Azure after the bootstrap has been performed.
