### ISSUE TITLE
Bug: RedundancyConfigurationNotAvailableInRegion

### ISSUE THREAD

**Issue by emlain** [Azure/ALZ-PowerShell-Module#291]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Infrastructure as Code Type? (Required)

terraform

### PowerShell Module Version (Optional)

4.2.3

### Bootstrap Module Version (Optional)

4.1.11

### Starter Module? (Required)

terraform - complete_multi_region

### Starter Module Version (Optional)

5.0.0

### Debug Output/Panic Output (Optional)

```shell

```

### Expected Behaviour (Required)

Is there any way to manage this setting on inputs.yaml file? 

### Actual Behaviour (Required)

New Azure region, like Italy North, doesn't have GZRS settings on Storage V2. Running the bootstrap I got this error:

Storage Account Name: "stoalzmgmita001pyhs"): performing Create: unexpected status 400 (400 Bad Request) with error: RedundancyConfigurationNotAvailableInRegion: The storage account failed to create due to redundancy configuration - Sku: Standard_GZRS, Kind: StorageV2 - not available in selected Region - italynorth. Please make sure the redundancy configuration selected is available in your region. For more information about redundancy configurations, see https://docs.microsoft.com/en-us/azure/storage/common/storage-redundancy

### Steps to Reproduce (Optional)

Fill in the inputs.yaml as follow:

```yaml
---
# For detailed instructions on using this file, visit:
# https://aka.ms/alz/accelerator/docs

# Basic Inputs
iac_type: "terraform"
bootstrap_module_name: "alz_local"
starter_module_name: "platform_landing_zone"

# Shared Interface Inputs
bootstrap_location: "italynorth"
starter_locations: ["italynorth", "northeurope"]
root_parent_management_group_id: ""
subscription_id_management: "xxxxx"
subscription_id_identity: "yyyyy"
subscription_id_connectivity: "zzzz"

# Bootstrap Inputs
target_directory: ""
create_bootstrap_resources_in_azure: true
bootstrap_subscription_id: "xxxxx"
service_name: "alz"
environment_name: "mgmt"
postfix_number: 1
grant_permissions_to_current_user: true

# Advanced Inputs
bootstrap_module_version: "latest"
starter_module_version: "latest"
#output_folder_path: "/accelerator/output"
```
