### ISSUE TITLE
Bug: Phase 3 of the accelerator fails

### ISSUE THREAD

**Issue by dansanabria** [Azure/ALZ-PowerShell-Module#365]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Infrastructure as Code Type? (Required)

terraform

### PowerShell Module Version (Optional)

4.2.9

### Starter Module? (Required)

terraform - platform_landing_zone

### Input arguments of the ALZ-PowerShell-Module (Optional)

Phase 3 step for pipeline is failing.

Pipeline does not appear as should and fails when run with the following error:

```
Invalid workflow file: .github/workflows/cd.yaml#L28](https://github.com/webuild-ai/alz-mgmt/actions/runs/15538179723/workflow)
error parsing called workflow
".github/workflows/cd.yaml"
-> "webuild-ai/alz-mgmt-templates/.github/workflows/cd-template.yaml@main"
: workflow was not found. See https://docs.github.com/actions/learn-github-actions/reusing-workflows#access-to-reusable-workflows for more information.
```

contents of `cd.yaml` are as follow:

```
---
name: 02 Azure Landing Zones Continuous Delivery
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Terraform Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - 'apply'
          - 'destroy'
      terraform_cli_version:
        description: 'Terraform CLI Version'
        required: true
        default: 'latest'
        type: string
permissions:
  contents: read
  id-token: write

jobs:
  plan_and_apply:
    uses: webuild-ai/alz-mgmt-templates/.github/workflows/cd-template.yaml@main
    name: 'CD'
    permissions:
      id-token: write
      contents: read
    with:
      terraform_action: ${{ inputs.terraform_action }}
      root_module_folder_relative_path: '.'
      terraform_cli_version: ${{ inputs.terraform_cli_version }}
```

### Debug Output/Panic Output (Optional)

```shell

```

### Expected Behaviour (Required)

Pipeline to complete and deploy to environment

### Actual Behaviour (Required)

Pipeline fails and converts name from 02 Azure Landing Zones Continuous Delivery to cd.yml

### Important Factoids (Optional)

Both repos `alz-mgmt` and `alz-mgmt-templates` are private repos in the same GitHub org.
